from . import wb_key_generator
from . import wb_license_tag
from . import wb_rate_limit_entry
from . import wb_license_event
from . import wb_license_key
from . import wb_activation_ticket
from . import wb_license_migration
from . import wb_license_trial
from . import wb_notification_log
from . import product_template
from . import sale_subscription
from . import res_partner
