from . import test_key_generator
from . import test_license_activation
from . import test_ticket_workflow
from . import test_dashboard
from . import test_install_registry
from . import test_lead_submission
from . import test_activation_consents
from . import test_module_version_check
from . import test_portal_downloads
from . import test_sprint2_security
from . import test_sprint3_security
from . import test_sprint5_polish
from . import test_subscription_promote
from . import test_mailing_list_sync
from . import test_pro_rata_invoice
from . import test_license_create_wizard
from . import test_auto_bind_lookup
from . import test_nfr_license
from . import test_hmac_signature
from . import test_retention
