from . import test_key_generator
from . import test_license_activation
from . import test_ticket_workflow
from . import test_dashboard
from . import test_install_registry
from . import test_lead_submission
from . import test_activation_consents
from . import test_module_version_check
from . import test_portal_downloads
